const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const CONFIG_FILE = path.join(ROOT_DIR, 'config.json');
const EVENTS_DIR = path.join(ROOT_DIR, 'data', 'events');
const SESSIONS_DIR = path.join(ROOT_DIR, 'data', 'sessions');
const UPLOADS_DIR = path.join(ROOT_DIR, 'uploads');

const DEFAULT_CONFIG = {
    title: 'Audric & Catherine',
    subtitle: 'A special moment awaits you!',
    descPremium: 'Enter your details to unveil a personalized wedding experience.',
    startText: 'START HERE',
    messageTemplate: 'Halo {name}! ✨\n\nKenangan Anda di ScribbleBooth sudah siap! Silakan lihat dan download melalui link folder di bawah ini:\n\n🔗 {link}\n\nTerima kasih sudah mampir!',
    emailSubject: 'Kenangan ScribbleBooth Anda sudah siap! ✨',
    logoUrl: "/uploads_logo/logo-placeholder.png",
    bottomLeftLogoUrl: '/logo-lumea.png',
    tutorialVideoUrl: "",
    resultVideoUrl: "",
    frameColor: "#3d3d3d",
    recordingDuration: 15,
    qrResetDuration: 45,
    readyTextMain: "Get your pen and look at mirror.",
    readyTextSub: "Hit the record button when you are ready.",
    reviewTextMain: "Please review your video,",
    reviewTextSub: "you can RETAKE or NEXT.",
    successTextMain: "Your memories are ready! ✨",
    successTextSub: "Scan this QR code to view and download your video and photo.",
    accentColor: "#d3bb7c",
    titleColor: "#f0e5c7",
    subtitleColor: "#f0e5c7",
    connectorColor: "#f0e5c7",
    descColor: "#cdcdcd",
    startTextColor: "#1a0f0a",
    startBtnBgColor: "#e7e5d8",
    formSubmitBtnBgColor: "#e7e5d8",
    readyRecordBtnBgColor: "#e7e5d8",
    recordingBtnBgColor: "#e11d48",
    reviewPhotoBtnBgColor: "#e7e5d8",
    photoRecordBtnBgColor: "#e7e5d8",
    photoBackBtnBgColor: "transparent",
    finalUploadBtnBgColor: "#e7e5d8",
    successDoneBtnBgColor: "#e7e5d8",
    readyTextColor: "#f0e5c7",
    reviewTextColor: "#f0e5c7",
    successTextColor: "#f0e5c7",
    formLabelName: "Name",
    formLabelNameColor: "#f0e5c7",
    formPlaceholderName: "Please input your name",
    formSubmitText: "SUBMIT",
    formSubmitTextColor: "#1a0f0a",
    readyHeaderTitle: "Ready To Play Words?",
    readyHeaderTitleColor: "#f0e5c7",
    readyHeaderSubtitle: "Write a simple letter to the Bride and Groom",
    readyHeaderSubtitleColor: "#f0e5c7",
    readyBackText: "BACK",
    readyBackTextColor: "#e7e5d8",
    reviewRetakeText: "RETAKE",
    reviewRetakeTextColor: "#e7e5d8",
    reviewPhotoText: "TAKE A PHOTO",
    reviewPhotoTextColor: "#1a0f0a",
    photoHeaderTitle: "Ready for Photo Session?",
    photoHeaderTitleColor: "#f0e5c7",
    photoHeaderSubtitle: "Strike a beautiful pose for the camera",
    photoHeaderSubtitleColor: "#f0e5c7",
    photoInstructionMain: "Look at the camera and smile.",
    photoInstructionSub: "Hit the shutter button when you are ready.",
    photoInstructionTextColor: "#f0e5c7",
    photoBackText: "BACK",
    photoBackTextColor: "#e7e5d8",
    finalHeaderTitle: "Review your session.",
    finalHeaderTitleColor: "#f0e5c7",
    finalVideoLabel: "VIDEO",
    finalPhotoLabel: "PHOTO",
    finalRetakeAllText: "RETAKE ALL",
    finalRetakeAllTextColor: "#e7e5d8",
    finalRetakePhotoText: "RETAKE PHOTO",
    finalRetakePhotoTextColor: "#e7e5d8",
    finalUploadText: "UPLOAD BOTH",
    finalUploadTextColor: "#1a0f0a",
    successFooterText: "Thank you for being part of this moment",
    successFooterTextColor: "#cdcdcd",
    successDoneText: "Done",
    successDoneTextColor: "#1a0f0a",
    eventDate: "2026-05-23",
    readyCdText: "Recording Begins in...",
    recordingCdText: "Recording...",
    photoCdText: "Taking Photo in...",
    previewPanelFooter: "Preview Your Moment",
    loadingPreviewText: "Loading Preview...",
    loadingTutorialText: "Loading Tutorial...",
    readyCountdownText: "Start Recording",
    photoCountdownText: "Take a Photo",
    resultLoadingText: "Loading your memories... ✨",
    resultErrorText: "Sorry, your session was not found or has expired.",
    resultProcessingText: "Processing your video & photo... please wait a moment. ✨<br><small style=\"font-size: 14px; opacity: 0.8; display: block; margin-top: 10px;\">Rendering process usually takes 10-15 seconds.</small>",
    resultSaveVideoText: "🎬 Save Your Video",
    resultSavePhotoText: "📸 Save Your Photo",
    resultFooterText: "Here's to the moments you'll always look back on - @momentsbylumea",
    resultBtnBgColor: "#721c24",
    resultBtnTextColor: "#ffffff",
    resultTextColor: "#f8fafc",
    resultPanelBgColor: "rgba(20, 15, 10, 0.85)",
    resultPanelBorderColor: "rgba(197, 160, 89, 0.3)",
    resultTitleColor: "#F0E5C7",
    resultLoadingTextColor: "#c5a059",
    resultErrorTextColor: "#ef4444",
    resultProcessingTextColor: "#c5a059",
    gallerySearchLabelColor: "#f0e5c7",
    galleryResetBtnBgColor: "#2a221b",
    galleryResetBtnTextColor: "#f0e5c7",
    galleryFooterTextColor: "#f0e5c7",
    galleryTitle: "Your Special Memories",
    gallerySearchLabel: "SEARCH GUEST NAME",
    gallerySearchPlaceholder: "Search by name...",
    galleryResetBtnText: "Reset Filters",
    galleryEmptyText: "No memories found yet.",
    galleryFooterText: "Here's to the moments you'll always look back on - @momentsbylumea",
    galleryTextColor: "#f0e5c7",
    galleryTitleColor: "#f0e5c7",
    galleryBgColor: "#0a0a0b",
    galleryFilterBgColor: "#140f0a",
    galleryFilterBorderColor: "#c5a059",
    galleryCardBgColor: "rgba(20, 15, 10, 0.7)",
    galleryCardBorderColor: "rgba(197, 160, 89, 0.2)",
    galleryCardNameColor: "#c5a059",
    galleryCardDateColor: "#a0a0a0",
    galleryDateColor: "#c5a059"
};

module.exports = { ROOT_DIR, CONFIG_FILE, EVENTS_DIR, SESSIONS_DIR, UPLOADS_DIR, DEFAULT_CONFIG };
